import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react";
import "../styles/index.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className="light">
            <body className={inter.className}>
                <SessionProvider refetchInterval={1} >
                    <NextUIProvider>
                        {children}
                    </NextUIProvider>
                </SessionProvider>
            </body>

        </html>
    );
}
